apiVersion: v1
kind: Secret
metadata:
  name: langbang-api-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://langbang:langbang@postgres:5432/langbang?schema=public"
  JWT_ACCESS_SECRET: "lab-access-secret-change-me"
  JWT_REFRESH_SECRET: "lab-refresh-secret-change-me"
  CLOUDINARY_CLOUD_NAME: "demo"
  CLOUDINARY_API_KEY: "demo"
  CLOUDINARY_API_SECRET: "demo"
  POSTGRES_DB: "langbang"
  POSTGRES_USER: "langbang"
  POSTGRES_PASSWORD: "langbang"
